### PR TITLE
Feature/multiqc 1.10

### PR DESCRIPTION
**Pull request by rernst**
- Fix FastQC parsing, azure id: 62362
- Solves 'Update multiqc to 1.10 and edit hsmetrics tables' #8 

Nextflow modules is set to dev-dx branch -> after https://github.com/UMCUGenetics/NextflowModules/pull/49 move to develop branch.

### CODE REVIEW

**Review by FiniDG — COMMENTED** [review]
in commit [4600bef7247df997f71d9360cb39dff1251add78](https://github.com/UMCUGenetics/DxNextflowWES/pull/29/commits/4600bef7247df997f71d9360cb39dff1251add78) (the last one here) I think I miss the following:
should WES.config also not be updated to 
`   withLabel: MultiQC_1_10 {`
same as commit [186ec45ebdd7c5011d8a8754b9159563342bf972](https://github.com/UMCUGenetics/DxNextflowWES/pull/29/commits/186ec45ebdd7c5011d8a8754b9159563342bf972)

**Comment by FiniDG** [comment]
I think I also miss the file:
MultiQC/1.10/MultiQC.nf
like in commit: [link](https://github.com/UMCUGenetics/NextflowModules/compare/1e85be9da95db3205cb1479d67519b100a115272...75592c866a60af12489838cf1a3b424dc0e6fe8e#diff-15a5f04cfc7a6dc1f62c452c29b268688c65e52a1021a9783951a6e73d512b54)

**Comment by FiniDG** [comment]
in the files changed.
Many have the `${params.optional}` at the end of the "script" part. But many also do not have it.
I am not sure of the significance, but does this need to be present in more files than I can see now?

**Comment by rernst** [comment]
> in the files changed.
> Many have the `${params.optional}` at the end of the "script" part. But many also do not have it.
> I am not sure of the significance, but does this need to be present in more files than I can see now?

That depends on the module and the tool the module is running. If a tool has optional parameters (like multiqc) we typically use an optional parameter. 

> I think I also miss the file:
> MultiQC/1.10/MultiQC.nf
> like in commit: [link](https://github.com/UMCUGenetics/NextflowModules/compare/1e85be9da95db3205cb1479d67519b100a115272...75592c866a60af12489838cf1a3b424dc0e6fe8e#diff-15a5f04cfc7a6dc1f62c452c29b268688c65e52a1021a9783951a6e73d512b54) (which shows the multiQC1.9)

See: https://github.com/UMCUGenetics/NextflowModules/blob/ecabe0a216678249c0aa2a79d32958ce71ad361a/MultiQC/1.10/MultiQC.nf and https://github.com/UMCUGenetics/NextflowModules/pull/49 

The update of modules is outside the scope of this repo, in the final develop to master PR we should make sure that everything is correctly linked.

**Review by FiniDG — APPROVED** [review]
with the "This branch has conflicts that must be resolved" solved and the changes in WES.config, I approve this merge.
I was a bit confused on how GitHub showed changes in modules, but my questions about them were answered clearly. The update of modules is outside the scope of this repo.

**Pull request merged**
